from .home import *
from .register import *
from .login import *
from .shop import *
from .leaderboard import *
from .profile import *
from .jobs import *
from .donate import *
from .notification import *
from .payment import *